### ISSUE TITLE
Unable to set fileUrl after authentication

### ISSUE THREAD

**Issue by HasijaPankaj** [kevnk/angular-dropbox#2]
I am able to view the files that are in my dropbox, after i choose one file; i see the following error in console..

angular.js:11496 TypeError: Cannot set property 'fileUrl' of undefined
    at angular-dropbox.js:248
    at Scope.$emit (angular.js:14532)
    at success (angular-dropbox.js:217)
    at Object.Dropbox._handleMessageEvent (angular-dropbox.js:72)
    at handler (angular-dropbox.js:141)

Can any one please help?

**Comment by kevnk** [comment]
Hi @HasijaPankaj — I haven't touched this project in 3 years so Angular and Dropbox chooser (https://www.dropbox.com/developers/chooser) have both been updated. Sorry. If you'd like to submit a pull request I'll be happy to add it in! Otherwise I'm afraid I can't help.

**Comment by HasijaPankaj** [comment]
Ok.. thank u :+1:
